"use client"

import localFont from "next/font/local"
import "./globals.css"
import Header from "./components/Header"
import { usePathname, useRouter } from "next/navigation"
import SideNav from "./components/SideNav"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }) {
  const pathName = usePathname()
  // console.log(router)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <div className="grid absolute grid-cols-12 w-full">
          {pathName.includes("/dashboard") ? (
            <div className=" top-0 col-span-3 ">
              <SideNav />
            </div>
          ) : (
            <div className="top-0 w-full col-span-12">
              <Header />
            </div>
          )}
          <div
            className={`relative p-4 ${
              pathName.includes("/dashboard") &&
              `bg-gradient-to-r  from-teal-950 to-sky-950`
            } w-full col-span-9  mx-auto `}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
